apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-2
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jdwillmsen@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - selector:
          dnsZones:
            - jdwkube.com
        dns01:
          webhook:
            groupName: jdwkube.com
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-key
                key: api-key
              secretKeySecretRef:
                name: porkbun-key
                key: secret-key