apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: longhorn-basic-auth
  data:
    - secretKey: auth
      remoteRef:
        key: longhorn-basic-auth
        property: htpasswd_string