apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: dbtech-atlas-schema-non
spec:
  credentials:
    scheme: postgres
    host: postgresql-cluster-non-rw.database.svc
    user: postgres
    passwordFrom:
      secretKeyRef:
        key: password
        name: postgresql-cluster-non-superuser
    database: dbtech_non
    port: 5432
    parameters:
      sslmode: disable
  schema:
    configMapKeyRef:
      key: schema.sql
      name: dbtech-postgresql-non-schema