---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jdwillmsen@gmail.com
    privateKeySecretRef:
      name: lets-encrypt-private-key
    solvers:
      - http01:
          ingress:
            class: public