ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: 'public'
    cert-manager.io/cluster-issuer: 'lets-encrypt'
  hosts:
    - host: dbui.jdw.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: pgweb-adminer
                port:
                  number: 80
  tls:
    - secreteName: pgweb-tls
      hosts:
        - dbui.jdw.com