apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example # Customisable
spec:
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: vault-secret-store
      kind: SecretStore
  selector:
    secret:
      name: postgresql-cluster-non-app # Source Kubernetes secret to be pushed
  data:
    - match:
        remoteRef:
          remoteKey: vault-secret-store # Remote reference (where the secret is going to be pushed)