apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jdwillmsen-github-app
  namespace: arc-runners
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: jdwillmsen-github-app
  data:
    - secretKey: github_app_id
      remoteRef:
        key: jdwillmsen-github-app
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: jdwillmsen-github-app
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: jdwillmsen-github-app
        property: github_app_private_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dotablaze-tech-github-app
  namespace: arc-runners
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: dotablaze-tech-github-app
  data:
    - secretKey: github_app_id
      remoteRef:
        key: dotablaze-tech-github-app
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: dotablaze-tech-github-app
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: dotablaze-tech-github-app
        property: github_app_private_key