apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: myapp
spec:
  connectionSecretRef:
    namespace: database
  credentials:
    scheme: auth
    host: postgresql-cluster-non-rw.database.svc
    user: postgres
    passwordFrom:
      secretKeyRef:
        key: password
        name: postgresql-cluster-non-superuser
    database: jdw
    port: 5432
    parameters:
      sslmode: disable
  schema:
    configMapKeyRef:
      key: schema.sql
      name: jdw-postgresql-non-schema