apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: porkbun
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: porkbun
  data:
    - secretKey: secret-key
      remoteRef:
        key: porkbun
        property: secret-key
    - secretKey: api-key
      remoteRef:
        key: porkbun
        property: api-key
