package talos

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"

	"github.com/jdw/talos-bootstrap/pkg/types"
)

// NodeConfig handles generation and management of Talos node configurations
type NodeConfig struct {
	cfg *types.Config
}

// NewNodeConfig creates a new NodeConfig generator
func NewNodeConfig(cfg *types.Config) *NodeConfig {
	return &NodeConfig{cfg: cfg}
}

// controlPlanePatchTemplate generates a YAML patch for control plane nodes.
// This is applied on top of the base controlplane.yaml generated by talosctl gen config
const controlPlanePatchTemplate = `machine:
  type: controlplane
  install:
    disk: /dev/{{ .DefaultDisk }}
    extraKernelArgs:
      - console=tty0
	  - console=ttyS0
  network:
	interfaces:
	  - interface: {{ .DefaultNetworkInterface }}
		dhcp: true
	extraHostEntries:
	  - ip: {{ .HAProxyIP }}
        aliases:
		  - {{ .ControlPlaneEndpoint }}
  sysctls:
    vm.nr_hugepages: "1024"
  kubelet:
    extraArgs:
	  rotate-server-certificates: "true"
  kernel:
	modules:
      - name: nvme_tcp
      - name: vfio_pci
      - name: zfs
cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  allowSchedulingOnControlPlanes: false
  apiServer:
    certSANs:
      - {{ .ControlPlaneEndpoint }}
	  - {{ .HAProxyIP }}
      - 127.0.0.1
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1
          kind: PodSecurityConfiguration
          exemptions:
            namespaces:
              - longhorn-system
`

// workerPatchTemplate generates a YAML patch for worker nodes.
// This is applied on top of the base worker.yaml generated by talosctl gen config
const workerPatchTemplate = `machine:
  type: worker
  install:
    disk: /dev/{{ .DefaultDisk }}
    extraKernelArgs:
      - console=tty0
	  - console=ttyS0
  network:
	interfaces:
	  - interface: {{ .DefaultNetworkInterface }}
		dhcp: true
	extraHostEntries:
	  - ip: {{ .HAProxyIP }}
        aliases:
		  - {{ .ControlPlaneEndpoint }}
  sysctls:
    vm.nr_hugepages: "1024"
  kubelet:
    extraArgs:
	  rotate-server-certificates: "true"
    extraMounts:
      - destination: /var/local
        type: bind
     	source: /var/local
		options:
		  - bind
		  - rshared
		  - rw
  kernel:
	modules:
      - name: nvme_tcp
      - name: vfio_pci
      - name: zfs
`

// templateData holds the values for config template rendering
type templateData struct {
	Hostname                string
	DefaultDisk             string
	DefaultNetworkInterface string
	HAProxyIP               string
	ControlPlaneEndpoint    string
	InstallerImage          string
	ClusterName             string
}

// GenerateBaseConfigs generate cluster secrets and base configs using talosctl.
// This produces secrets.yaml, control-plane.yaml, worker.yaml, and talosconfig in SecretsDir
func (nc *NodeConfig) GenerateBaseConfigs() error {
	secretsDir := nc.cfg.SecretsDir
	if err := os.MkdirAll(secretsDir, 0700); err != nil {
		return fmt.Errorf("cannot create secrets directory %s: %w", secretsDir, err)
	}

	secretsFile := filepath.Join(secretsDir, "secrets.yaml")

	// Generate secrets if they don't exist
	if _, err := os.Stat(secretsFile); os.IsNotExist(err) {
		cmd := exec.Command("talosctl", "gen", "secrets", "-o", secretsFile)
		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("talosctl gen secrets: %w, output: %s", err, string(output))
		}
		if err := os.Chmod(secretsFile, 0600); err != nil {
			return fmt.Errorf("cannot chmod secrets: %w", err)
		}
	}

	// Generate base configs using the secrets
	additionalSANs := fmt.Sprintf("%s,%s,127.0.0.1",
		nc.cfg.HAProxyIP.String(), nc.cfg.ControlPlaneEndpoint)
	clusterEndpoint := fmt.Sprintf("https://%s:6443", nc.cfg.ControlPlaneEndpoint)

	// Run talosctl gen config in a temp dir, then move the output files
	tmpDir, err := os.MkdirTemp("", "talos-gen-config-*")
	if err != nil {
		return fmt.Errorf("cannot create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	cmd := exec.Command("talosctl", "gen", "config",
		"--with-secrets", secretsFile,
		"--kubernetes-version", nc.cfg.KubernetesVersion,
		"--talos-version", nc.cfg.TalosVersion,
		"--install-image", nc.cfg.InstallerImage,
		"--additional-sans", additionalSANs,
		"--output-dir", tmpDir,
		nc.cfg.ClusterName, clusterEndpoint,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("talosctl gen config: %w, output: %s", err, string(output))
	}

	// Move generated files to secrets dir
	moves := map[string]string{
		"controlplane.yaml": filepath.Join(secretsDir, "controlplane.yaml"),
		"worker.yaml":       filepath.Join(secretsDir, "worker.yaml"),
		"talosconfig":       filepath.Join(secretsDir, "talosconfig"),
	}

	for src, dst := range moves {
		srcPath := filepath.Join(tmpDir, src)
		if _, err := os.Stat(srcPath); err != nil {
			continue
		}
		data, err := os.ReadFile(srcPath)
		if err != nil {
			return fmt.Errorf("cannot read %s: %w", srcPath, err)
		}
		if err := os.WriteFile(dst, data, 0600); err != nil {
			return fmt.Errorf("cannot write %s: %w", dst, err)
		}
	}

	return nil
}

// Generate creates a Talos node config by generating a patch file and applying it
// to the base config using talosctl machineconfig patch. Returns the SHA256 hash.
func (nc *NodeConfig) Generate(spec *types.NodeSpec, outputDir string) (string, error) {
	data := templateData{
		Hostname:                spec.Name,
		DefaultDisk:             nc.cfg.DefaultDisk,
		DefaultNetworkInterface: nc.cfg.DefaultNetworkInterface,
		HAProxyIP:               nc.cfg.HAProxyIP.String(),
		ControlPlaneEndpoint:    nc.cfg.ControlPlaneEndpoint,
		InstallerImage:          nc.cfg.InstallerImage,
		ClusterName:             nc.cfg.ClusterName,
	}

	var tmplStr string
	var baseConfigName string
	switch spec.Role {
	case types.RoleControlPlane:
		tmplStr = controlPlanePatchTemplate
		baseConfigName = "controlplane.yaml"
	case types.RoleWorker:
		tmplStr = workerPatchTemplate
		baseConfigName = "worker.yaml"
	default:
		return "", fmt.Errorf("unknown node role: %s", spec.Role)
	}

	// Ensure base configs exists
	baseConfig := filepath.Join(nc.cfg.SecretsDir, baseConfigName)
	if _, err := os.Stat(baseConfig); os.IsNotExist(err) {
		if err := nc.GenerateBaseConfigs(); err != nil {
			return "", fmt.Errorf("cannot generate base configs: %w", err)
		}
	}

	// Render patch template
	tmpl, err := template.New("nodePatch").Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	// Write patch to temp file
	patchDir := filepath.Join(outputDir, ".patches")
	if err := os.MkdirAll(patchDir, 0755); err != nil {
		return "", fmt.Errorf("create patch dir: %w", err)
	}

	patchFile := filepath.Join(patchDir, fmt.Sprintf("%s-%d.yaml", spec.Role, spec.VMID))
	if err := os.WriteFile(patchFile, buf.Bytes(), 0600); err != nil {
		return "", fmt.Errorf("write patch file: %w", err)
	}
	defer os.Remove(patchFile)

	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return "", fmt.Errorf("create output directory: %w", err)
	}

	// Apply patch using talosctl machineconfig patch
	outputPath := filepath.Join(outputDir, fmt.Sprintf("node-%s-%d.yaml", spec.Role, spec.VMID))
	cmd := exec.Command("talosctl", "machineconfig", "patch", baseConfig,
		"--patch", "@"+patchFile,
		"--output", outputPath,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("talosctl machineconfig patch: %w, output: %s", err, string(output))
	}

	// Compute SHA256 hash of the generated config
	configBytes, err := os.ReadFile(outputPath)
	if err != nil {
		return "", fmt.Errorf("read generated configs: %w", err)
	}
	hash := sha256.Sum256(configBytes)
	return hex.EncodeToString(hash[:]), nil
}

// ConfigPath returns the expected path for a node's config file based on the output directory, VMID, and role.
func (nc *NodeConfig) ConfigPath(outputDir string, vmid types.VMID, role types.Role) string {
	filename := fmt.Sprintf("node-%s-%d.yaml", role, vmid)
	return filepath.Join(outputDir, filename)
}

// HashFile computes the SHA256 hash of an existing config file for drift detection
func HashFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:]), nil
}
